include:
  - package:very_good_analysis/analysis_options.yaml 
  - package:bloc_lint/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.mocks.dart"
    - "**/*.pb.dart"
    - "lib/features/training/presentation/widgets/custom_context_menu.dart"

linter:
  rules:
    prefer_int_literals: false
    omit_local_variable_types: false
    flutter_style_todos: false
    public_member_api_docs: false