FROM nginx:alpine

# Copy build artifacts from the build stage
COPY nginx-default.conf /etc/nginx/conf.d/default.conf
COPY build/web/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
